# This workflow will build the package on all possible platforms for a release

name: release

on:
  release:
    types: [created]

jobs:

  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: download build script
        run: wget https://raw.githubusercontent.com/donuts-are-good/release.sh/master/release.sh && chmod +x release.sh

      - name: build binaries
        run: ./release.sh --name "random-json" --version "1.0.0"

      - name: Upload a artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: ./BUILDS/*
          if-no-files-found: warn
